templates={
	"cms":{
		"image_slider":{
			"change_image_slider":"iiits/cms/image_slider/"
		},
		"admissions":{	
			"change_ug_admissions":"iiits/cms/ug_admissions",
			"change_pg_admissions":"iiits/cms/pg_admissions",
			"change_mtech_admissions":"iiits/cms/",
			"change_ms_admissions":"iiits/cms/",
			"change_phd_admissions":"iiits/cms/",
			"change_fee_structure":"iiits/cms/",
			"change_policy":"iiits/cms/",
			"change_financial_assistance":"iiits/cms/",
		},
		"academics":{	
			"change_time_table":"",
			"change_curriculum":"",
			"change_courses":"",
			"change_almanac":"",
		},
		"research":{
			"add_research_centre":"",
			"add_to_portfolio":"",
			"add_research_students":"",
			"add_publications":"",
			"change_research_centre_profile_description":"",
		},
		"campus_life":{

		},
		"news":{
			"add_news":"iiits/news/add.html"
		},
		"about":{
			"change_board_governers":"",
			"change_about_sricity":"",
			"change_reaching_iiit":"",
			"change_location":"",
			"add_developer":"",
		},


	}
	"display":{
	"display_image_slider":"",
	"display_navbar":"",
	"display_faculty_page":"",
	"display_faculty_list":"",
	"display_faculty_profile":"",
	"display_newsroom":"",
	"display_media":"",
	"display_students_page":"",
	"display_students_profile":"",
	"display_staff_list":"",
	"display_":""
	}
}

urls={
	"cms":{
		"news":{
			"add_success":"/success/add/newsroom/"
		},
		"notice":{
			"add_success":"/success/add/notice/"
		}
	}
}	
values={
	"IMAGE_SLIDER_MAX_PHOTOS":"5",
	"PROFILE_PAGINATION_MAX_ENTRIES":"10",
	"NEWS_PAGINATION_MAX_ENTRIES":"5",
}
strings={
	"site_title":"IIITS - Indian Institute of Information Technology Chittoor, SriCity"
}