templates={
	"cms":{
		"image_slider":{
			"change":"iiits/cms/image_slider/"
		},
		"admissions":{	
			"undergraduate":"iiits/cms/ug_admissions",
			"postgraduate":"iiits/cms/pg_admissions",
			"mtech":"iiits/cms/",
			"ms":"iiits/cms/",
			"phd":"iiits/cms/",
			"fee_structure":"iiits/cms/",
			"policy":"iiits/cms/",
			"financial_assistance":"iiits/cms/",
		},
		"academics":{	
			"change_time_table":"",
			"change_curriculum":"",
			"change_courses":"",
			"change_almanac":"",
		},
		"research":{
			"add_research_centre":"",
			"add_to_portfolio":"",
			"add_research_students":"",
			"add_publications":"",
			"change_research_centre_profile_description":"",
		},
		"campus_life":{

		},
		"news":{
			"add_news":"iiits/news/add.html"
		},
		"notice":{
			"add_notice":"iiits/notice/add.html"
		},
		"about":{
			"change_board_governers":"",
			"change_about_sricity":"",
			"change_reaching_iiit":"",
			"change_location":"",
			"add_developer":"",
		},


	},
	"site":{
		"admissions":{
			"home":"iiits/site/admissions/home.html",
			"undergraduate":"iiits/site/admissions/undergraduate.html",
			"postgraduate":"iiits/site/admissions/postgraduate.html",
		},

		"site_image_slider":"",
		"site_navbar":"",
		"site_faculty_page":"",
		"site_faculty_list":"",
		"site_faculty_profile":"",
		"site_newsroom":"",
		"site_media":"",
		"site_students_page":"",
		"site_students_profile":"",
		"site_staff_list":"",
		"site_":""
	},
	"base":{
		"admissions":"iiits/base/base_admissions.html"
	}
}

urls={
	"cms":{
		"news":{
			"add_success":"/success/add/newsroom/"
		},
		"notice":{
			"add_success":"/success/add/notice/"
		}
	}
}	
values={
	"IMAGE_SLIDER_MAX_PHOTOS":"5",
	"PROFILE_PAGINATION_MAX_ENTRIES":"10",
	"NEWS_PAGINATION_MAX_ENTRIES":"5",
}
strings={
	"site_title":"IIITS - Indian Institute of Information Technology Chittoor, SriCity"
}