# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iiits', '0003_auto_20160226_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='iiits/static/iiits/images/faculty/')),
                ('institute', models.TextField()),
                ('courses', models.TextField()),
                ('public_uri_name', models.CharField(db_index=True, default='NA', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='public_uri_name',
            field=models.CharField(db_index=True, default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(upload_to='iiits/static/iiits/images/faculty/'),
        ),
    ]
