# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0004_auto_20160228_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='achievements',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='other_info',
            field=models.TextField(default='NA'),
        ),
    ]
