# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0005_auto_20160228_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('content', models.TextField(default='NA')),
                ('fileupload', models.FileField(blank=True, null=True, upload_to='/static/iiits/files/news/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='/static/iiits/images/news/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='visitingfaculty',
            name='photo',
            field=models.ImageField(upload_to='/static/iiits/images/faculty/'),
        ),
    ]
