# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0006_auto_20160229_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsFeeStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tution_fee', models.TextField()),
                ('admission', models.TextField()),
                ('caution_deposit', models.TextField()),
                ('hostel_water_electric', models.TextField()),
                ('mess', models.TextField()),
                ('textbooks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeno', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('fileupload', models.FileField(blank=True, null=True, upload_to='/static/iiits/files/notice/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
