# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0007_admissionsfeestructure_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsFinancialAssistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('order_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
