# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0010_auto_20160324_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsFeeModeofPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsFeeModeofPaymentNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
    ]
