# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0011_admissionsfeemodeofpayment_admissionsfeemodeofpaymentnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('fileupload', models.FileField(upload_to='iiits/static/iiits/files/academics/timetables/')),
                ('session', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
