# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0012_academicstimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.TextField()),
                ('seats', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicsResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'CALENDAR', b'Academic Calendar'), (b'HOLIDAYS', b'Holidays'), (b'Almanac', b'Almanac')], db_index=True, default=(b'CALENDAR', b'Academic Calendar'), max_length=50)),
                ('session', models.CharField(choices=[(b'MONSOON', b'Monsoon'), (b'MONSOON', b'Spring')], default=(b'MONSOON', b'Monsoon'), max_length=20)),
                ('year', models.CharField(choices=[(b'2013', b'2013'), (b'2014', b'2014'), (b'2015', b'2015'), (b'2016', b'2016'), (b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020'), (b'2021', b'2021'), (b'2022', b'2022'), (b'2023', b'2023'), (b'2024', b'2024'), (b'2025', b'2025'), (b'2026', b'2026'), (b'2027', b'2027'), (b'2028', b'2028'), (b'2029', b'2029'), (b'2030', b'2030'), (b'2031', b'2031'), (b'2032', b'2032'), (b'2033', b'2033')], default=(b'2016', b'2016'), max_length=10)),
                ('fileupload', models.FileField(upload_to=b'iiits/static/iiits/files/academics/resources/')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[(b'FEE', b'Fee Payment'), (b'ACADEMIC_PROGRAMMES', b'Academic Programmes'), (b'UG_CURRICULUM', b'Under Graduate Curriculum'), (b'UG_CURRICULUM_BENCHMARKING', b'Under Graduate Curriculum Benchmarking')], db_index=True, default=(b'FEE', b'Fee Payment'), max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AdmissionsFeeModeofPaymentNotes',
        ),
        migrations.RemoveField(
            model_name='academicstimetable',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='academicstimetable',
            name='semester',
        ),
        migrations.AddField(
            model_name='academicstimetable',
            name='batchnsem',
            field=models.CharField(choices=[(b'UG1SEM1', b'UG1 Semester-1'), (b'UG1SEM2', b'UG1 Semester-2'), (b'UG2SEM3', b'UG2 Semester-3'), (b'UG2SEM4', b'UG2 Semester-4'), (b'UG3SEM5', b'UG3 Semester-5'), (b'UG3SEM6', b'UG3 Semester-6'), (b'UG4SEM7', b'UG4 Semester-7'), (b'UG4SEM8', b'UG4 Semester-8')], db_index=True, default=(b'UG1SEM1', b'UG1 Semester-1'), max_length=20),
        ),
        migrations.AlterField(
            model_name='academicstimetable',
            name='branch',
            field=models.CharField(choices=[(b'CSE', b'Computer Science Engineering'), (b'ECE', b'Electronics and Communications Engineering')], default=(b'CSE', b'Computer Science Engineering'), max_length=20),
        ),
        migrations.AlterField(
            model_name='academicstimetable',
            name='session',
            field=models.CharField(choices=[(b'MONSOON', b'Monsoon'), (b'MONSOON', b'Spring')], default=(b'MONSOON', b'Monsoon'), max_length=20),
        ),
        migrations.AlterField(
            model_name='academicstimetable',
            name='year',
            field=models.CharField(choices=[(b'2013', b'2013'), (b'2014', b'2014'), (b'2015', b'2015'), (b'2016', b'2016'), (b'2017', b'2017'), (b'2018', b'2018'), (b'2019', b'2019'), (b'2020', b'2020'), (b'2021', b'2021'), (b'2022', b'2022'), (b'2023', b'2023'), (b'2024', b'2024'), (b'2025', b'2025'), (b'2026', b'2026'), (b'2027', b'2027'), (b'2028', b'2028'), (b'2029', b'2029'), (b'2030', b'2030'), (b'2031', b'2031'), (b'2032', b'2032'), (b'2033', b'2033')], default=(b'2016', b'2016'), max_length=10),
        ),
    ]
