# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0013_auto_20160324_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionsPolicy',
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(choices=[(b'FEE', b'Fee Payment'), (b'POLICY', b'Admissions Policy'), (b'ACADEMIC_PROGRAMMES', b'Academic Programmes'), (b'UG_CURRICULUM', b'Under Graduate Curriculum'), (b'UG_CURRICULUM_BENCHMARKING', b'Under Graduate Curriculum Benchmarking')], db_index=True, default=(b'FEE', b'Fee Payment'), max_length=100),
        ),
    ]
