# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-25 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iiits', '0014_auto_20160324_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('research_areas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_areas', models.TextField()),
                ('faculty', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'iiits/static/iiits/files/research/portfolio/')),
                ('fileupload', models.FileField(blank=True, null=True, upload_to=b'iiits/static/iiits/files/research/portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_centres', models.TextField()),
                ('mentors', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='academicsresources',
            name='title',
            field=models.CharField(choices=[(b'CALENDAR', b'Academic Calendar'), (b'HOLIDAYS', b'Holidays'), (b'Almanac', b'Almanac'), (b'CURRICULUM_UG1_SEM1', b'UG1 Semester-1 Curriculum'), (b'CURRICULUM_UG1_SEM2', b'UG1 Semester-2 Curriculum')], db_index=True, default=(b'CALENDAR', b'Academic Calendar'), max_length=50),
        ),
    ]
