# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0015_auto_20160325_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(db_index=True, max_length=20)),
                ('name', models.TextField()),
                ('faculties', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='public_uri_name',
            field=models.CharField(db_index=True, default='NA', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='visitingfaculty',
            name='public_uri_name',
            field=models.CharField(db_index=True, default='NA', max_length=100, unique=True),
        ),
    ]
