# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0018_auto_20160404_0854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
