# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0020_imageslider_researchcentreprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='research_areas',
            field=models.TextField(default=''),
        ),
    ]
