# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0021_auto_20160423_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingfaculty',
            name='photo',
            field=models.ImageField(upload_to='iiits/static/iiits/images/faculty/'),
        ),
    ]
