# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0022_auto_20160423_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingfaculty',
            name='title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='iiits.FacultyTitle'),
            preserve_default=False,
        ),
    ]
