# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0023_visitingfaculty_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='visitingfaculty',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiits.Institute'),
        ),
    ]
