# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0024_auto_20160423_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(upload_to='iiits/static/iiits/images/imageslider'),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='order_no',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='iiits/static/iiits/files/news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='iiits/static/iiits/images/news/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to='iiits/static/iiits/files/notice/'),
        ),
    ]
