# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0029_auto_20160426_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
    ]
