# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0031_auto_20160506_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerNonFacultyPosition',
            fields=[
                ('career_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iiits.Career')),
                ('career_type', models.CharField(max_length=255)),
                ('details', models.TextField(null=True)),
            ],
            bases=('iiits.career', models.Model),
        ),
        migrations.CreateModel(
            name='ConsultancyContract',
            fields=[
                ('career_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='iiits.Career')),
            ],
            bases=('iiits.career', models.Model),
        ),
    ]
