# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0032_careernonfacultyposition_consultancycontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='iiits/static/iiits/images/topstories/')),
                ('body', models.TextField()),
                ('show_on_home_page', models.BooleanField(default=False)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiits.News')),
            ],
        ),
    ]
