# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0033_topstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topstory',
            old_name='link',
            new_name='news_link',
        ),
    ]
