# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0035_careerfacultyposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='description',
            field=models.TextField(default=b'No description provided', verbose_name='No description provided'),
            preserve_default=False,
        ),
    ]
