# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 17:58
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0036_career_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
