# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 19:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0039_auto_20160528_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='iiits/static/iiits/images/campus_life/events/')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='iiits/static/iiits/images/campus_life/facilities/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLifeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='iiits/static/iiits/images/campus_life/student_life/')),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='iiits/static/iiits/images/faculty/'),
        ),
    ]
