# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 15:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0039_auto_20160621_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', ckeditor.fields.RichTextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
