# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0040_auto_20160529_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
