# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 15:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0040_newsstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='detailed',
            field=ckeditor.fields.RichTextField(default='details not available'),
        ),
    ]
