# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 20:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0041_auto_20160529_1926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.AddField(
            model_name='faculty',
            name='courses',
            field=ckeditor.fields.RichTextField(default='Not available at the moment'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='research_areas',
            field=ckeditor.fields.RichTextField(default='Not available'),
        ),
    ]
