# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0041_newsstory_detailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='detailed',
        ),
        migrations.AlterField(
            model_name='newsstory',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
