# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0043_auto_20160529_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='contact_no',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='show_contact_no',
            new_name='show_contact',
        ),
    ]
