# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0044_publication_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
