# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0045_publication_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='researchstudent',
            name='mentors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchstudent',
            name='research_centres',
            field=models.TextField(),
        ),
    ]
