# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0046_auto_20160630_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchstudent',
            name='photo',
            field=models.ImageField(default=b'NA', upload_to=b'iiits/static/iiits/files/research/portfolio/'),
            preserve_default=False,
        ),
    ]
