# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 02:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0048_auto_20160630_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLifeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CampusLifeSubEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('picture', models.ImageField(upload_to='iiits/images/campuslife/contents')),
                ('show_picture', models.BooleanField(default=False)),
                ('links', ckeditor.fields.RichTextField()),
                ('show_links', models.BooleanField(default=False)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iiits.CampusLifeEntity')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='StudentLifeArticle',
        ),
    ]
