# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0049_auto_20160705_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuslifeentity',
            name='rank',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
