# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0051_auto_20160707_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_tender',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 14, 14, 13, 26, 60149, tzinfo=utc)),
        ),
    ]
