# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0052_auto_20160707_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='tender_tags',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 14, 14, 14, 53, 980007, tzinfo=utc)),
        ),
    ]
