# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-08 03:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0054_auto_20160707_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 15, 3, 31, 23, 322078, tzinfo=utc)),
        ),
    ]
