# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-13 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0056_auto_20160708_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='iiits/images/misc/')),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 12, 2, 10, 20736, tzinfo=utc)),
        ),
    ]
