# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0060_auto_20160717_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 24, 8, 24, 19, 614254, tzinfo=utc)),
        ),
    ]
