# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('iiits', '0061_auto_20160717_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='photo',
            field=models.ImageField(upload_to='iiits/static/iiits/images/faculty/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 24, 11, 57, 19, 504439, tzinfo=utc)),
        ),
    ]
